### ISSUE TITLE
运行run-ubuntu-desktop.bat脚本VcXsrv server 黑屏，没有出现图形化桌面

### ISSUE THREAD

**Issue by coconutmango** [WangJiaxiang96/WSL-Guideline#1]
你好：
前面按照你的方法一步一步都好了，图形化界面也出现了，最后编辑脚本run-ubuntu-desktop.bat：然后运行此脚本，图形化界面没有出现，不知是我哪里疏漏了，
run-ubuntu-desktop.bat脚本如下：
```
cd /d %~dp0
start vcxsrv.exe  :0 -clipboard -wgl -keyhook -nodecoration
sleep 2powershell.exe -WindowStyle Hidden -c ubuntu
```
/etc/profile配置如下：
```
  if [ "$BASH" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
export DISPLAY=localhost:0
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
nohup compiz >/dev/null 2>&1 &
nohup plank >/dev/null 2>&1 &
```
其中下面的这些是我后来加上的：
```
export DISPLAY=localhost:0
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
nohup compiz >/dev/null 2>&1 &
nohup plank >/dev/null 2>&1 &
```

最后运行run-ubuntu-desktop.bat 后没有出现图形化桌面，请指教。

**Comment by iWangJiaxiang** [comment]
你好，那个最后执行compiz的时候别把输出都给dev/null了，看看会报什么错~对了，在compiz之前是要执行ccsm命令的哦

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: cocoa <notifications@github.com>
发送时间: Thursday, May 31, 2018 5:13:01 PM
收件人: WangJiaxiang96/WSL-Guideline
抄送: Subscribed
主题: [WangJiaxiang96/WSL-Guideline] 运行run-ubuntu-desktop.bat脚本VcXsrv server 黑屏，没有出现图形化桌面 (#1)


你好：
前面按照你的方法一步一步都好了，图形化界面也出现了，最后编辑脚本run-ubuntu-desktop.bat：然后运行此脚本，图形化界面没有出现，不知是我哪里疏漏了，
run-ubuntu-desktop.bat脚本如下：

cd /d %~dp0
start vcxsrv.exe  :0 -clipboard -wgl -keyhook -nodecoration
sleep 2powershell.exe -WindowStyle Hidden -c ubuntu


/etc/profile配置如下：

  if [ "$BASH" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
export DISPLAY=localhost:0
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
nohup compiz >/dev/null 2>&1 &
nohup plank >/dev/null 2>&1 &


上面的这些：

export DISPLAY=localhost:0
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
nohup compiz >/dev/null 2>&1 &
nohup plank >/dev/null 2>&1 &


是我后来加上的，
最后运行run-ubuntu-desktop.bat 后没有出现图形化桌面，请指教。

―
