### ISSUE TITLE
求助安装桌面的问题

### ISSUE THREAD

**Issue by 0xhyperdan** [WangJiaxiang96/WSL-Guideline#2]
按照教程，到安装桌面，装完后 ubuntu 桌面背景是黑的，看不到桌面。
![image](https://user-images.githubusercontent.com/16094265/44724684-03ff0c00-ab06-11e8-8561-9d7fccbc888c.png)
换过，ubuntu 的所有版本，都不行，vcxsrv 版本是最新的。

**Comment by xnng** [comment]
「桌面背景是黑的」指的是没有壁纸了还是桌面完全不能用了，如果只是没壁纸，手动设置下壁纸试试

**Comment by 0xhyperdan** [comment]
桌面完全不能用，在文件管理 点 Desktop 还报错。

**Comment by 0xhyperdan** [comment]
作者把教程更新一下把，目前新的，ubuntu 18.0.4 的版本是不需要 ccsm compiz 这两步骤了， 直接安装完，ubuntu-desktop后 重启一下 dbus 服务。开 VcXsrv 设置一下后 wsl 里面执行 gnome-session 后就可以了。

**Comment by iWangJiaxiang** [comment]
好的，多谢提醒！

**Comment by stelectronic** [comment]
> 作者把教程更新一下把，目前新的，ubuntu 18.0.4 的版本是不需要 ccsm compiz 这两步骤了， 直接安装完，ubuntu-desktop后 重启一下 dbus 服务。开 VcXsrv 设置一下后 wsl 里面执行 gnome-session 后就可以了。

我和你一样的情况, 18.04版本, 按照你说的, 我先启动win10上的VcXsrv, 再重启dbus还是这样啊

**Comment by ZhyCong** [comment]
问题解决了吗，我也是遇到这个问题

**Comment by ZhyCong** [comment]
> > 作者把教程更新一下把，目前新的，ubuntu 18.0.4 的版本是不需要 ccsm compiz 这两步骤了， 直接安装完，ubuntu-desktop后 重启一下 dbus 服务。开 VcXsrv 设置一下后 wsl 里面执行 gnome-session 后就可以了。
> 
> 我和你一样的情况, 18.04版本, 按照你说的, 我先启动win10上的VcXsrv, 再重启dbus还是这样啊

最后怎样解决的呀
