### ISSUE TITLE
 ubuntu 16.04 通过脚本提高效率

### ISSUE THREAD

**Issue by rorypeck** [WangJiaxiang96/WSL-Guideline#3]
安装的是Ubuntu16.04，按照教程里的方法：
文件系统
  WSL和Windows主系统之间的文件系统是可以互相访问的。
  如果在WSL中访问Windows系统的文件，可在根目录下看到对应Windows盘符字母的文件夹，通过这些文件夹即可访问Windows的文件系统。
  如果在Windows系统中访问WSL的文件，可在Windows系统中找到已安装Linux发行版的应用数据文件夹，所有Linux系统的数据都在那个文件夹（通过应用商店安装的Linux发行版本质上也是一个应用）。Linux发行版的数据文件夹在路径内，在文件夹内我们会看到在WSL中的根目录。 

      但是，无法找到Ubuntu，请教一下，Ubuntu 16.04应该如何启动？

**Comment by iWangJiaxiang** [comment]
软件包名称并不是完全等于"Ubuntu"，通常会包含公司、版本、唯一标识等信息。

比如我的1804版本Ubuntu的包名为`CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc`。

尝试找一下`C`开头的文件夹？

**Comment by rorypeck** [comment]
我按照您写的教程找到了，比较是18.04，那么如何用powershell打开呢？
powershell.exe -WindowStyle Hidden -c ubuntu这个命令只能打开ubuntu，而不能打开16.04或18.04

**Comment by iWangJiaxiang** [comment]
在`Powershell`输入发行版名称（例如`ubuntu`）默认启动已安装的最新发行版，如果同时安装了同一发行版的多个版本，如`ubuntu-16.04`和`ubuntu-18.04`，`ubuntu`命令总会启动最新的18.04版。

如果需要启动指定版本的发行版，请按以下步骤操作：

1. 打开`powershell`。
2. 执行`wsl -l`命令，查看系统已安装的发行版。
3. 执行`wsl -d <想启动的发行版名称>`命令。

回到问题，您只需将命令中的`ubuntu`换成`"wsl -d ubuntu-16.04"`即可，完整如下：

    powershell.exe -WindowStyle Hidden -c "wsl -d ubuntu-16.04"

**Comment by rorypeck** [comment]
好的，谢谢。确实可以，wsl刚开始用，不知道能否替代双系统
